# Optional: GitHub Actions workflow for Azure deployment
# This will automatically deploy to Azure when you push to master branch
#
# To use this:
# 1. In Azure Portal, go to your Web App → "Deployment Center"
# 2. Choose GitHub Actions (instead of just GitHub)
# 3. Azure will generate a workflow file similar to this
# 4. Or manually add Azure publish profile as GitHub secret named AZURE_WEBAPP_PUBLISH_PROFILE

name: Deploy to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10'
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 🔄 Checkout code
      uses: actions/checkout@v3
      
    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: 📦 Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    # Uncomment the following steps after setting up Azure credentials
    # - name: 🚀 Deploy to Azure Web App
    #   uses: azure/webapps-deploy@v2
    #   with:
    #     app-name: 'your-app-name'  # Replace with your Azure Web App name
    #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
